export const pedidosPruebas = {
  "printers": [
    {
      "Id_impresora": 1,
      "Nombre_modelo": "Creality Ender 3",
      "Ubicación_imp": "Casa",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://m.media-amazon.com/images/I/61L4aoIqYOL._AC_SX466_.jpg",
      "Precio_servicio": 0.05,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 220,
      "Max_alto": 220,
      "Precision": 100,
      "Colores_disponibles": ["Blanco", "Negro", "Rojo", "Azul"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Creality"
    },
    {
      "Id_impresora": 2,
      "Nombre_modelo": "Prusa i3 MK3S+",
      "Ubicación_imp": "Oficina",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://www.prusa3d.com/content/images/product/default/224.jpg",
      "Precio_servicio": 0.10,
      "Unidades_max": 1,
      "Velo_fabricacion": 200,
      "Max_ancho": 250,
      "Max_alto": 210,
      "Precision": 50,
      "Colores_disponibles": ["Negro", "Gris", "Naranja"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Prusa Research"
    },
    {
      "Id_impresora": 3,
      "Nombre_modelo": "Elegoo Mars 3",
      "Ubicación_imp": "Estudio",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://www.elegoo.com/cdn/shop/files/elegoo-mars-3-resin-3d-printer-1_610x610_crop_center.jpg?v=1706524688",
      "Precio_servicio": 0.20,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 140,
      "Max_alto": 180,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Blanco", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Elegoo"
    },
    {
      "Id_impresora": 4,
      "Nombre_modelo": "Anycubic Photon Mono X",
      "Ubicación_imp": "Taller",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://store.anycubic.com/cdn/shop/products/PhotonMonoX_1_540x.jpg?v=1682043040",
      "Precio_servicio": 0.25,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 192,
      "Max_alto": 245,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Anycubic"
    },
    {
      "Id_impresora": 5,
      "Nombre_modelo": "Creality Ender 5",
      "Ubicación_imp": "Casa",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://www.prusa3d.com/content/images/product/default/224.jpg",
      "Precio_servicio": 0.06,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 220,
      "Max_alto": 220,
      "Precision": 100,
      "Colores_disponibles": ["Negro", "Gris", "Rojo"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Creality"
    },
    {
      "Id_impresora": 6,
      "Nombre_modelo": "Anycubic Mega S",
        "Ubicación_imp": "Oficina",
        "Tipo_impresora": "FDM",
        "Foto_impresora": "https://www.prusa3d.com/content/images/product/default/224.jpg",
        "Precio_servicio": 0.07,
        "Unidades_max": 1,
        "Velo_fabricacion": 100,
        "Max_ancho": 210,
        "Max_alto": 210,
        "Precision": 100,
        "Colores_disponibles": ["Negro", "Gris", "Azul"],
        "Acabados_disponibles": ["Mate", "Brillante"],
        "Fabricante": "Anycubic"
    },
    {
      "Id_impresora": 7,
      "Nombre_modelo": "Monoprice Maker Select Plus",
      "Ubicación_imp": "Estudio",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://www.prusa3d.com/content/images/product/default/224.jpg",
      "Precio_servicio": 0.08,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 220,
      "Max_alto": 220,
      "Precision": 100,
      "Colores_disponibles": ["Negro", "Gris"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Monoprice"
    },
    {
      "Id_impresora": 8,
      "Nombre_modelo": "Geeetech A10M",
      "Ubicación_imp": "Taller",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://images-na.ssl-images-amazon.com/images/G/01/error/154._TTD_.jpg",
      "Precio_servicio": 0.09,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 220,
      "Max_alto": 220,
      "Precision": 100,
      "Colores_disponibles": ["Negro", "Gris", "Rojo"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Geeetech"
    },
    {
      "Id_impresora": 9,
      "Nombre_modelo": "Prusa Mini",
      "Ubicación_imp": "Casa",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://www.prusa3d.com/_next/image/?url=%2Fimg%2FMK404_covered.webp&w=640&q=75",
      "Precio_servicio": 0.11,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 180,
      "Max_alto": 130,
      "Precision": 50,
      "Colores_disponibles": ["Negro", "Gris", "Naranja"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Prusa Research"
    },
    {
      "Id_impresora": 10,
      "Nombre_modelo": "Creality Ender 6",
      "Ubicación_imp": "Oficina",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://images-na.ssl-images-amazon.com/images/G/01/error/en_US/185._TTD_.jpg",
      "Precio_servicio": 0.12,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 250,
      "Max_alto": 250,
      "Precision": 100,
      "Colores_disponibles": ["Negro", "Gris", "Rojo"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Creality"
    },
    {
      "Id_impresora": 11,
      "Nombre_modelo": "Anycubic Chiron",
      "Ubicación_imp": "Estudio",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://images-na.ssl-images-amazon.com/images/G/01/error/108._TTD_.jpg",
      "Precio_servicio": 0.13,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 400,
      "Max_alto": 400,
      "Precision": 100,
      "Colores_disponibles": ["Negro", "Gris", "Azul"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Anycubic"
    },
    {
      "Id_impresora": 12,
      "Nombre_modelo": "Elegoo Saturn",
      "Ubicación_imp": "Taller",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://www.prusa3d.com/content/images/product/default/224.jpg",
      "Precio_servicio": 0.26,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 219,
      "Max_alto": 120,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Elegoo"
    },
    {
      "Id_impresora": 13,
      "Nombre_modelo": "Prusa SL1",
      "Ubicación_imp": "Casa",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://www.prusa3d.com/_next/image/?url=%2Fimg%2FMK404_covered.webp&w=640&q=75",
      "Precio_servicio": 0.27,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 220,
      "Max_alto": 120,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Prusa Research"
    },
    {
      "Id_impresora": 14,
      "Nombre_modelo": "Anycubic Mono X 6K",
      "Ubicación_imp": "Oficina",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://www.prusa3d.com/content/images/product/default/224.jpg",
      "Precio_servicio": 0.28,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 292,
      "Max_alto": 165,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Anycubic"
    },
    {
      "Id_impresora": 15,
      "Nombre_modelo": "Elegoo Mars 3 Pro",
      "Ubicación_imp": "Estudio",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://www.elegoo.com/cdn/shop/files/JupiterSE_1_610x610_crop_center.jpg?v=1705051360",
      "Precio_servicio": 0.29,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 140,
      "Max_alto": 180,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Blanco", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Elegoo"
    },
    {
      "Id_impresora": 16,
      "Nombre_modelo": "Creality LD-002R",
      "Ubicación_imp": "Taller",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://www.elegoo.com/cdn/shop/files/JupiterSE_2_610x610_crop_center.jpg?v=1705051356",
      "Precio_servicio": 0.30,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 120,
      "Max_alto": 220,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Creality"
    },
    {
      "Id_impresora": 17,
      "Nombre_modelo": "Phrozen Sonic Mini 4K",
      "Ubicación_imp": "Casa",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://phrozen3d.com/cdn/shop/files/SonicMega8KS_1400x1600_1_03859aca-2744-4efd-9d81-41c6d7ccca36.png?v=1692178357&width=700",
      "Precio_servicio": 0.31,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 133,
      "Max_alto": 80,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Phrozen"
    },
    {
      "Id_impresora": 18,
      "Nombre_modelo": "Anycubic Photon Zero",
      "Ubicación_imp": "Oficina",
      "Tipo_impresora": "SLA",
      "Foto_impresora": "https://images-na.ssl-images-amazon.com/images/G/01/error/154._TTD_.jpg",
      "Precio_servicio": 0.32,
      "Unidades_max": 1,
      "Velo_fabricacion": 60,
      "Max_ancho": 98,
      "Max_alto": 55,
      "Precision": 50,
      "Colores_disponibles": ["Gris", "Negro"],
      "Acabados_disponibles": ["Mate"],
      "Fabricante": "Anycubic"
    },
    {
      "Id_impresora": 19,
      "Nombre_modelo": "Longer LK5 Pro",
      "Ubicación_imp": "Estudio",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://www.longer3d.com/cdn/shop/files/10_df939b56-ca70-4b00-80b1-4a298f266f6f.jpg?v=1700895648&width=900",
      "Precio_servicio": 0.14,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 300,
      "Max_alto": 300,
      "Precision": 100,
      "Colores_disponibles": ["Negro", "Gris", "Rojo"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Longer"
    },
    {
      "Id_impresora": 20,
      "Nombre_modelo": "Artillery Sidewinder X1",
      "Ubicación_imp": "Taller",
      "Tipo_impresora": "FDM",
      "Foto_impresora": "https://www.artillery3d.com/cdn/shop/files/X2-2_1440x1440.jpg?v=1706085398",
      "Precio_servicio": 0.15,
      "Unidades_max": 1,
      "Velo_fabricacion": 100,
      "Max_ancho": 300,
      "Max_alto": 300,
      "Precision": 100,
      "Colores_disponibles": ["Negro", "Gris"],
      "Acabados_disponibles": ["Mate", "Brillante"],
      "Fabricante": "Artillery"
    }    
  ]
  ,
  "total": 20,
  "skip": 0,
  "limit": 20
};